"""
On-device redaction of video chunks, before they are uploaded.

Each closed 10-second chunk is OCR'd (PaddleOCR PP-OCR models on ONNX
Runtime, via RapidOCR), checked with the Presidio rules and masked with
OpenCV (cudai_privacy.video). Only the redacted chunk ever leaves this
computer; the local video.mp4 stays original.

OCR is CPU-heavy, so it runs in a separate, low-priority worker process
(`backend.py --redaction-worker`): it cannot slow capture down much or take a
recording with it if it crashes. When the screen changes a lot, redaction
falls behind and uploads catch up later.

Per chunk (paths relative to the recording):
  redacted/<part>          masked copy (only when something was masked)
  redacted/<part>.json     result: file to upload, masks, timings, version
  ocr/<part>.jsonl         OCR content layer (text with sensitive values
                           replaced, boxes, masks) for every OCR'd frame
"""

import json
import os
import subprocess
import sys
import threading
import time

from . import timing
from .logger import logger

REDACTION_VERSION = 1
OCR_THREADS = 4  # leave cores for capture and the rest of the Mac
MAX_ATTEMPTS = 3


# Per-chunk results -------------------------------------------------------------

def needs_redaction(part: str) -> bool:
    """Pause-gap clips are black frames generated by cudAI."""
    return "/gap_" not in part


def meta_path(recording_path: str, part: str) -> str:
    return os.path.join(recording_path, "redacted", part + ".json")


def load_meta(recording_path: str, part: str) -> dict | None:
    try:
        with open(meta_path(recording_path, part), "r", encoding="utf-8") as f:
            return json.load(f)
    except (OSError, ValueError):
        return None


def _write_json(path: str, data) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(data, f)
    os.replace(tmp, path)


def upload_source(recording_path: str, part: str) -> dict | None:
    """What to upload for a video part, or None while it is not redacted yet."""
    if not needs_redaction(part):
        return {"file": os.path.join(recording_path, part), "ocr": None}
    meta = load_meta(recording_path, part)
    if not meta or meta.get("version") != REDACTION_VERSION or meta.get("error"):
        return None
    return {
        "file": os.path.join(recording_path, meta["file"]),
        "ocr": os.path.join(recording_path, meta["ocr"]) if meta.get("ocr") else None,
    }


SUMMARY_FILE = "redaction_summary.json"


def write_summary(recording_path: str, parts: list) -> dict:
    """Totals over every redacted chunk, for the manifest's privacy block."""
    from collections import Counter

    from importlib.metadata import PackageNotFoundError, version

    try:
        presidio_version = version("presidio-analyzer")
    except PackageNotFoundError:  # packaged app without dist metadata
        presidio_version = "2.x"

    entities, chunks, masked, ocr_frames = Counter(), 0, 0, 0
    for part in parts:
        if not needs_redaction(part):
            continue
        meta = load_meta(recording_path, part) or {}
        chunks += 1
        masked += bool(meta.get("masked"))
        ocr_frames += meta.get("ocr_frames") or 0
        entities.update(meta.get("entities") or {})
    summary = {
        "version": REDACTION_VERSION,
        "where": "on device, before upload",
        "detector": f"Microsoft Presidio {presidio_version} (cudai_privacy rules)",
        "ocr": "PaddleOCR PP-OCR det+rec on ONNX Runtime (RapidOCR)",
        "masking": "OpenCV solid fill",
        "chunks": chunks,
        "masked_chunks": masked,
        "ocr_frames": ocr_frames,
        "masked_values": dict(entities),
    }
    _write_json(os.path.join(recording_path, SUMMARY_FILE), summary)
    return summary


# OCR engine --------------------------------------------------------------------

class RapidOcr:
    """PaddleOCR (PP-OCR det + rec) on ONNX Runtime, CPU."""

    def __init__(self, threads: int = OCR_THREADS):
        from rapidocr import RapidOCR

        self.engine = RapidOCR(params={
            "Global.use_cls": False,  # screen text is upright
            "Global.log_level": "warning",
            "EngineConfig.onnxruntime.intra_op_num_threads": threads,
        })

    def __call__(self, image) -> list:
        if image.shape[0] < 8 or image.shape[1] < 8:
            return []
        result = self.engine(image)
        if result.boxes is None or result.txts is None:
            return []
        lines = []
        for poly, text, score in zip(result.boxes, result.txts, result.scores):
            xs, ys = [p[0] for p in poly], [p[1] for p in poly]
            lines.append(((min(xs), min(ys), max(xs), max(ys)), text, score))
        return lines


def redact_chunk(recording_path: str, part: str, ocr) -> dict:
    """Redact one chunk; writes the outputs above and returns the result."""
    from cudai_privacy.video import redact_video

    from .utils import VIDEO_FPS, get_ffmpeg_path, h264_encoder_args

    src = os.path.join(recording_path, part)
    redacted_rel = f"redacted/{part}"
    dst = os.path.join(recording_path, redacted_rel)
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    tmp = dst[: -len(".mp4")] + ".tmp.mp4"

    def on_timing(stage, seconds, **extra):
        end = time.time()
        timing.record(recording_path, stage, end - seconds, end, chunk=part, **extra)

    with timing.stage(recording_path, "redact_chunk", chunk=part) as info:
        result = redact_video(src, tmp, ocr, get_ffmpeg_path(), h264_encoder_args(),
                              fps=VIDEO_FPS, on_timing=on_timing)
        info.update(masked=result["masked"], ocr_frames=result["ocr_frames"], entities=result["entities"])
    if result["masked"]:
        os.replace(tmp, dst)

    ocr_rel = f"ocr/{part}.jsonl"
    ocr_path = os.path.join(recording_path, ocr_rel)
    os.makedirs(os.path.dirname(ocr_path), exist_ok=True)
    with open(ocr_path + ".tmp", "w", encoding="utf-8") as f:
        for row in result["layer"]:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")
    os.replace(ocr_path + ".tmp", ocr_path)

    meta = {
        "version": REDACTION_VERSION,
        "file": redacted_rel if result["masked"] else part,
        "ocr": ocr_rel,
        "masked": result["masked"],
        "frames": result["frames"],
        "ocr_frames": result["ocr_frames"],
        "entities": result["entities"],
        "ocr_engine": "rapidocr-onnx (PaddleOCR PP-OCR)",
    }
    _write_json(meta_path(recording_path, part), meta)
    return meta


# Worker process ----------------------------------------------------------------

def worker_command() -> list:
    if getattr(sys, "frozen", False):  # packaged app: the backend binary itself
        return [sys.executable, "--redaction-worker"]
    backend = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "backend.py")
    return [sys.executable, backend, "--redaction-worker"]


def worker_main() -> None:
    """Entry point of the worker: one JSON job per stdin line, one reply per line."""
    # Replies go to a private copy of stdout; anything else printed (logs)
    # goes to stderr so it cannot corrupt the protocol.
    replies = os.fdopen(os.dup(1), "w", buffering=1)
    os.dup2(2, 1)
    # `kill -USR1 <pid>` prints every thread's stack to stderr (diagnostics).
    import faulthandler
    import signal

    faulthandler.register(signal.SIGUSR1, all_threads=True)
    try:
        os.nice(10)
    except OSError:
        pass
    ocr = RapidOcr()
    for line in sys.stdin:
        try:
            job = json.loads(line)
            reply = {"ok": True, "meta": redact_chunk(job["recording"], job["part"], ocr)}
        except Exception as e:  # reported to the parent, which retries
            reply = {"ok": False, "error": f"{type(e).__name__}: {e}"}
        replies.write(json.dumps(reply) + "\n")


class RedactionWorker:
    """The worker process, started on first use and restarted if it dies."""

    def __init__(self):
        self.process = None

    def run(self, recording_path: str, part: str) -> dict:
        if self.process is None or self.process.poll() is not None:
            self.process = subprocess.Popen(
                worker_command(), stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL, text=True, bufsize=1,
            )
        try:
            self.process.stdin.write(json.dumps({"recording": recording_path, "part": part}) + "\n")
            self.process.stdin.flush()
            line = self.process.stdout.readline()
        except (BrokenPipeError, OSError) as e:
            line, error = "", str(e)
        else:
            error = "redaction worker exited"
        if not line:
            self.stop()
            return {"ok": False, "error": error}
        return json.loads(line)

    def stop(self) -> None:
        if self.process is not None:
            try:
                self.process.kill()
                self.process.wait(timeout=5)
            except Exception:
                pass
            self.process = None


# Scheduler -----------------------------------------------------------------------

class RedactionManager(threading.Thread):
    """
    Redacts chunks as they close (the live recording first), then any chunk of
    a finished recording still waiting, e.g. after a restart.
    """

    POLL_SECONDS = 1.0

    def __init__(self, upload_manager, recordings_dir: str | None = None, worker=None):
        super().__init__(daemon=True, name="cudai-redaction")
        from .utils import RECORDING_DIR

        self.upload_manager = upload_manager
        self.recordings_dir = recordings_dir or RECORDING_DIR
        self.worker = worker or RedactionWorker()
        self._first_seen = {}  # (recording, part) -> time first seen ready
        self._attempts = {}
        self._done = set()  # finished recordings with every chunk redacted
        self._stopped = False
        self.status = {"backlog": 0, "current": None, "last_seconds": None, "last_error": None}

    def stop(self) -> None:
        self._stopped = True
        self.worker.stop()

    def run(self) -> None:
        while not self._stopped:
            try:
                if not self.step():
                    time.sleep(self.POLL_SECONDS)
            except Exception:
                logger.exception("redaction: unexpected error")
                time.sleep(5)

    def pending(self) -> list:
        """(recording, part) still to redact, live recording first."""
        from .upload import is_configured, is_eligible, load_config

        if not is_configured(load_config()):
            return []
        jobs = []
        live = self.upload_manager.live
        if live and is_eligible(live[0]):
            for chunk in live[1].ready_chunks():
                if needs_redaction(chunk["path"]) and load_meta(live[0], chunk["path"]) is None:
                    jobs.append((live[0], chunk["path"]))
        jobs += self._finished_jobs(live[0] if live else None)
        now = time.time()
        for job in jobs:
            self._first_seen.setdefault(job, now)
        self.status["backlog"] = len(jobs)
        return jobs

    def _finished_jobs(self, live_path: str | None) -> list:
        from .upload import _read_json, _video_parts, is_eligible

        jobs = []
        if not os.path.isdir(self.recordings_dir):
            return jobs
        for name in sorted(os.listdir(self.recordings_dir)):
            path = os.path.join(self.recordings_dir, name)
            if path in self._done or path == live_path or not os.path.isdir(os.path.join(path, "chunks")):
                continue
            if not is_eligible(path):
                continue
            parts = _video_parts(_read_json(os.path.join(path, "metadata.json")))
            if not parts:
                continue  # still recording or being finalized
            todo = [(path, p) for p in parts if needs_redaction(p) and load_meta(path, p) is None
                    and os.path.exists(os.path.join(path, p))]
            if todo:
                jobs += todo
            else:
                self._done.add(path)
        return jobs

    def step(self) -> bool:
        """Redact the next pending chunk. False when there was nothing to do."""
        jobs = self.pending()
        if not jobs:
            self.status["current"] = None
            return False
        recording, part = job = jobs[0]
        self.status["current"] = part
        started = time.time()
        timing.record(recording, "redaction_queue_wait", self._first_seen.pop(job, started), started, chunk=part)
        reply = self.worker.run(recording, part)
        self.status["last_seconds"] = round(time.time() - started, 2)
        if reply.get("ok"):
            self._attempts.pop(job, None)
            self.status["last_error"] = None
            self.upload_manager.wake()
            return True
        attempts = self._attempts[job] = self._attempts.get(job, 0) + 1
        self.status["last_error"] = reply.get("error")
        logger.error(f"redaction: {part} failed ({attempts}/{MAX_ATTEMPTS}): {reply.get('error')}")
        if attempts >= MAX_ATTEMPTS:
            # Never upload it unredacted: mark it failed so it is skipped.
            _write_json(meta_path(recording, part), {
                "version": REDACTION_VERSION, "error": reply.get("error"),
            })
        return True
